"""Shared constants for Telegram/Copilot runtime behavior."""

DEFAULT_USER_INPUT_TIMEOUT_SECONDS = 300
DEFAULT_BINARY_DOWNLOAD_MAX_BYTES = 45 * 1024 * 1024
DEFAULT_BINARY_DOWNLOAD_TIMEOUT_SECONDS = 120
DEFAULT_SHUTDOWN_DRAIN_TIMEOUT_SECONDS = 60
DEFAULT_SKILL_TOOL_MAX_CALLS_PER_ASK = 4
HEARTBEAT_INTERVAL_SECONDS = 15
PROGRESS_EDIT_THROTTLE_SECONDS = 1.2
PROGRESS_PREVIEW_CHARS = 1200
VALID_REASONING_EFFORTS = {"low", "medium", "high", "xhigh"}

IGNORED_SCAN_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
}
